name: Deploy to Linode

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
    
    - name: Install dependencies
      run: | 
        npm ci
        cd frontend && npm ci
    
    - name: Build frontend
      run: npm run build
    
    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/antoniabuilds.dev
          git pull origin main
          npm ci --only=production
          npm run build
          pm2 restart antoniabuilds || pm2 start app.js --name antoniabuilds
